---
title: "Coursera Writeup"
output: html_notebook
---

To complete this project, I first identified the columns that did not contain NA values and took a subset of the training and testing data so that only these columns were included in my analysis. Afterwards, I tried testing different models such as LDA, QDA, boosting, and random forest, and based on the accuracy results on the trianing data with 10 fold cross validation, QDA ended up being the most effective model, with around 90% accuracy on the training data. This suggests that the out of sample error rate would be greater than 10% as performance on an out of sample test set is typically wose than the training data a model is based upon. Without any normalizing, these type of results were able to be achieved, and they could only be imporved upon if I were to normalize all data, and maybe even perform PCA to identify variables whose information is repeated and not needed, which would reduce the complexity of the model.
```{r}
library(AppliedPredictiveModeling)
library(ggplot2)
library(caret)
library(caret)
set.seed(1000)
training <- readr::read_csv("C:/Users/binfo/Downloads/pml-training.csv")
testing <- readr::read_csv("C:/Users/binfo/Downloads/pml-testing.csv")
#cleaning data by only selecting columns without N/A values 
training <- subset(training, select=c(new_window,	num_window,	roll_belt,	pitch_belt,	yaw_belt,	total_accel_belt,gyros_belt_x,	gyros_belt_y,	gyros_belt_z,	accel_belt_x,	accel_belt_y,	accel_belt_z,	magnet_belt_x,	magnet_belt_y,	magnet_belt_z,	roll_arm,	pitch_arm,	yaw_arm,	total_accel_arm,
gyros_arm_x,	gyros_arm_y,	gyros_arm_z,	accel_arm_x,	accel_arm_y,	accel_arm_z,	magnet_arm_x,	magnet_arm_y,	magnet_arm_z,roll_dumbbell,	pitch_dumbbell,	yaw_dumbbell,total_accel_dumbbell,gyros_dumbbell_x,	gyros_dumbbell_y,	gyros_dumbbell_z,	accel_dumbbell_x,	accel_dumbbell_y,	accel_dumbbell_z, magnet_dumbbell_x,	magnet_dumbbell_y	,magnet_dumbbell_z,	roll_forearm,	pitch_forearm,	yaw_forearm, gyros_forearm_x,	gyros_forearm_y,	gyros_forearm_z,	accel_forearm_x,	accel_forearm_y,	accel_forearm_z,	magnet_forearm_x,	magnet_forearm_y,	magnet_forearm_z,	classe))

testing <- subset(testing, select=c(new_window,	num_window,	roll_belt,	pitch_belt,	yaw_belt,	total_accel_belt,gyros_belt_x,	gyros_belt_y,	gyros_belt_z,	accel_belt_x,	accel_belt_y,	accel_belt_z,	magnet_belt_x,	magnet_belt_y,	magnet_belt_z, roll_arm,	pitch_arm,	yaw_arm,	total_accel_arm,
gyros_arm_x,	gyros_arm_y,	gyros_arm_z,	accel_arm_x,	accel_arm_y,	accel_arm_z,	magnet_arm_x,	magnet_arm_y,	magnet_arm_z,roll_dumbbell,	pitch_dumbbell,	yaw_dumbbell,total_accel_dumbbell,gyros_dumbbell_x,	gyros_dumbbell_y,	gyros_dumbbell_z,	accel_dumbbell_x,	accel_dumbbell_y,	accel_dumbbell_z, magnet_dumbbell_x,	magnet_dumbbell_y	,magnet_dumbbell_z,	roll_forearm,	pitch_forearm,	yaw_forearm, gyros_forearm_x,	gyros_forearm_y,	gyros_forearm_z,	accel_forearm_x,	accel_forearm_y,	accel_forearm_z,	magnet_forearm_x,	magnet_forearm_y,	magnet_forearm_z))

control<-trainControl(method="cv", number = 10)
train(classe ~ ., data = training,method = "gbm",prox=TRUE, trControl= control)
train(classe ~ ., data = training,method = "rf",prox=TRUE, trControl= control)
train(classe ~ ., data = training,method = "lda",prox=TRUE, trControl= control)
modFit <- train(classe ~ ., data = training,method = "qda",prox=TRUE, trControl= control)
predictions <- predict(modFit, testing)
predictions

```


